import { KEYS, setAll } from './storage';
import type {
  Department, Staff, Patient, Room, Appointment,
  Prescription, LabOrder, Invoice, InventoryItem,
  Notification, AuditLog, QueueEntry, ConsultationNote, VitalRecord,
} from '../types';

// ─── Departments ──────────────────────────────────────────────────────────────
const departments: Department[] = [
  { id: 'dept-1', name: 'Cardiology',      description: 'Heart and cardiovascular care',       headDoctorId: 'staff-2', floor: '3rd', totalBeds: 30, availableBeds: 8,  color: '#ef4444', icon: 'heart' },
  { id: 'dept-2', name: 'Neurology',       description: 'Brain and nervous system disorders',  headDoctorId: 'staff-3', floor: '4th', totalBeds: 25, availableBeds: 6,  color: '#8b5cf6', icon: 'brain' },
  { id: 'dept-3', name: 'Pediatrics',      description: 'Healthcare for infants and children', headDoctorId: 'staff-4', floor: '2nd', totalBeds: 35, availableBeds: 14, color: '#10b981', icon: 'baby' },
  { id: 'dept-4', name: 'Orthopedics',     description: 'Bone, joint and muscle treatment',    headDoctorId: 'staff-5', floor: '3rd', totalBeds: 20, availableBeds: 5,  color: '#f59e0b', icon: 'bone' },
  { id: 'dept-5', name: 'Emergency',       description: '24/7 emergency and trauma care',      headDoctorId: 'staff-6', floor: '1st', totalBeds: 40, availableBeds: 12, color: '#dc2626', icon: 'zap' },
  { id: 'dept-6', name: 'General Medicine',description: 'Primary and general healthcare',      headDoctorId: 'staff-7', floor: '2nd', totalBeds: 50, availableBeds: 20, color: '#3b82f6', icon: 'stethoscope' },
  { id: 'dept-7', name: 'Gynecology',      description: 'Women\'s reproductive health',        headDoctorId: 'staff-8', floor: '4th', totalBeds: 28, availableBeds: 9,  color: '#ec4899', icon: 'heart' },
  { id: 'dept-8', name: 'Dermatology',     description: 'Skin, hair and nail conditions',      headDoctorId: 'staff-9', floor: '2nd', totalBeds: 15, availableBeds: 7,  color: '#14b8a6', icon: 'sparkles' },
];

// ─── Staff ────────────────────────────────────────────────────────────────────
const staff: Staff[] = [
  // Admin
  { id: 'staff-1',  staffNumber: 'AD-001', firstName: 'James',   lastName: 'Carter',    email: 'admin@careflow.com',       phone: '+1-555-0101', role: 'ADMIN',        departmentId: undefined,  specialization: undefined,           licenseNumber: undefined,      dateJoined: '2020-01-15', status: 'active',    workingDays: ['monday','tuesday','wednesday','thursday','friday'], workingHours: { start: '08:00', end: '17:00' } },
  // Doctors
  { id: 'staff-2',  staffNumber: 'DR-001', firstName: 'Sarah',   lastName: 'Mitchell',  email: 'dr.mitchell@careflow.com', phone: '+1-555-0102', role: 'DOCTOR',       departmentId: 'dept-1',   specialization: 'Interventional Cardiology', licenseNumber: 'LIC-10234', dateJoined: '2018-03-10', status: 'active',    workingDays: ['monday','tuesday','wednesday','thursday','friday'], workingHours: { start: '08:00', end: '16:00' } },
  { id: 'staff-3',  staffNumber: 'DR-002', firstName: 'Robert',  lastName: 'Chen',      email: 'dr.chen@careflow.com',     phone: '+1-555-0103', role: 'DOCTOR',       departmentId: 'dept-2',   specialization: 'Neurosurgery',              licenseNumber: 'LIC-10235', dateJoined: '2017-06-01', status: 'active',    workingDays: ['monday','tuesday','wednesday','thursday','friday'], workingHours: { start: '09:00', end: '17:00' } },
  { id: 'staff-4',  staffNumber: 'DR-003', firstName: 'Emily',   lastName: 'Rodriguez', email: 'dr.rodriguez@careflow.com',phone: '+1-555-0104', role: 'DOCTOR',       departmentId: 'dept-3',   specialization: 'Neonatology',               licenseNumber: 'LIC-10236', dateJoined: '2019-09-15', status: 'active',    workingDays: ['monday','tuesday','wednesday','thursday','saturday'], workingHours: { start: '08:00', end: '15:00' } },
  { id: 'staff-5',  staffNumber: 'DR-004', firstName: 'Michael', lastName: 'Thompson',  email: 'dr.thompson@careflow.com', phone: '+1-555-0105', role: 'DOCTOR',       departmentId: 'dept-4',   specialization: 'Sports Medicine',           licenseNumber: 'LIC-10237', dateJoined: '2016-11-20', status: 'active',    workingDays: ['monday','tuesday','wednesday','thursday','friday'], workingHours: { start: '08:00', end: '16:00' } },
  { id: 'staff-6',  staffNumber: 'DR-005', firstName: 'Aisha',   lastName: 'Okafor',    email: 'dr.okafor@careflow.com',   phone: '+1-555-0106', role: 'DOCTOR',       departmentId: 'dept-5',   specialization: 'Emergency Medicine',        licenseNumber: 'LIC-10238', dateJoined: '2021-02-01', status: 'active',    workingDays: ['monday','tuesday','wednesday','thursday','friday','saturday','sunday'], workingHours: { start: '07:00', end: '19:00' } },
  { id: 'staff-7',  staffNumber: 'DR-006', firstName: 'William', lastName: 'Park',      email: 'dr.park@careflow.com',     phone: '+1-555-0107', role: 'DOCTOR',       departmentId: 'dept-6',   specialization: 'Internal Medicine',         licenseNumber: 'LIC-10239', dateJoined: '2015-07-14', status: 'active',    workingDays: ['monday','tuesday','wednesday','thursday','friday'], workingHours: { start: '08:00', end: '17:00' } },
  { id: 'staff-8',  staffNumber: 'DR-007', firstName: 'Priya',   lastName: 'Sharma',    email: 'dr.sharma@careflow.com',   phone: '+1-555-0108', role: 'DOCTOR',       departmentId: 'dept-7',   specialization: 'Obstetrics & Gynecology',   licenseNumber: 'LIC-10240', dateJoined: '2020-05-20', status: 'active',    workingDays: ['monday','tuesday','wednesday','thursday','friday'], workingHours: { start: '09:00', end: '17:00' } },
  { id: 'staff-9',  staffNumber: 'DR-008', firstName: 'David',   lastName: 'Wilson',    email: 'dr.wilson@careflow.com',   phone: '+1-555-0109', role: 'DOCTOR',       departmentId: 'dept-8',   specialization: 'Cosmetic Dermatology',      licenseNumber: 'LIC-10241', dateJoined: '2022-01-10', status: 'on_leave',  workingDays: ['monday','tuesday','wednesday','thursday','friday'], workingHours: { start: '10:00', end: '18:00' } },
  // Receptionists
  { id: 'staff-10', staffNumber: 'RC-001', firstName: 'Anna',    lastName: 'Martinez',  email: 'anna@careflow.com',        phone: '+1-555-0110', role: 'RECEPTIONIST', departmentId: undefined,  specialization: undefined,           licenseNumber: undefined,      dateJoined: '2021-03-15', status: 'active',    workingDays: ['monday','tuesday','wednesday','thursday','friday'], workingHours: { start: '07:00', end: '15:00' } },
  { id: 'staff-11', staffNumber: 'RC-002', firstName: 'Kevin',   lastName: 'Brown',     email: 'kevin@careflow.com',       phone: '+1-555-0111', role: 'RECEPTIONIST', departmentId: undefined,  specialization: undefined,           licenseNumber: undefined,      dateJoined: '2022-06-01', status: 'active',    workingDays: ['monday','tuesday','wednesday','thursday','friday'], workingHours: { start: '15:00', end: '23:00' } },
  { id: 'staff-12', staffNumber: 'RC-003', firstName: 'Lisa',    lastName: 'Johnson',   email: 'lisa@careflow.com',        phone: '+1-555-0112', role: 'RECEPTIONIST', departmentId: undefined,  specialization: undefined,           licenseNumber: undefined,      dateJoined: '2023-01-10', status: 'active',    workingDays: ['saturday','sunday'], workingHours: { start: '08:00', end: '20:00' } },
  // Nurses
  { id: 'staff-13', staffNumber: 'NR-001', firstName: 'Maria',   lastName: 'Santos',    email: 'maria@careflow.com',       phone: '+1-555-0113', role: 'NURSE',        departmentId: 'dept-6',   specialization: undefined,           licenseNumber: undefined,      dateJoined: '2020-08-20', status: 'active',    workingDays: ['monday','tuesday','wednesday','thursday','friday'], workingHours: { start: '07:00', end: '15:00' } },
  { id: 'staff-14', staffNumber: 'NR-002', firstName: 'Tom',     lastName: 'Williams',  email: 'tom@careflow.com',         phone: '+1-555-0114', role: 'NURSE',        departmentId: 'dept-5',   specialization: undefined,           licenseNumber: undefined,      dateJoined: '2021-11-05', status: 'active',    workingDays: ['monday','tuesday','wednesday','thursday','friday','saturday'], workingHours: { start: '15:00', end: '23:00' } },
  { id: 'staff-15', staffNumber: 'NR-003', firstName: 'Grace',   lastName: 'Lee',       email: 'grace@careflow.com',       phone: '+1-555-0115', role: 'NURSE',        departmentId: 'dept-1',   specialization: undefined,           licenseNumber: undefined,      dateJoined: '2022-03-01', status: 'active',    workingDays: ['monday','tuesday','wednesday','thursday','friday'], workingHours: { start: '08:00', end: '16:00' } },
];

// ─── Patients ─────────────────────────────────────────────────────────────────
const patients: Patient[] = [
  { id: 'pat-1',  patientNumber: 'PT-0001', firstName: 'John',      lastName: 'Anderson',  email: 'john.anderson@email.com',   phone: '+1-555-1001', dateOfBirth: '1978-04-12', gender: 'male',   bloodType: 'A+',      address: '123 Maple St',       city: 'Springfield', emergencyContactName: 'Mary Anderson',    emergencyContactPhone: '+1-555-1002', allergies: ['Penicillin'],              chronicConditions: ['Hypertension', 'Type 2 Diabetes'], insuranceProvider: 'BlueCross', insuranceNumber: 'BC-98234', status: 'active', registeredAt: '2023-01-10T09:00:00Z', assignedDoctorId: 'staff-2' },
  { id: 'pat-2',  patientNumber: 'PT-0002', firstName: 'Emma',      lastName: 'Wilson',    email: 'emma.wilson@email.com',     phone: '+1-555-1003', dateOfBirth: '1990-07-23', gender: 'female', bloodType: 'B+',      address: '456 Oak Ave',        city: 'Riverside',   emergencyContactName: 'Tom Wilson',       emergencyContactPhone: '+1-555-1004', allergies: ['Sulfa'],                   chronicConditions: ['Migraines'],               insuranceProvider: 'Aetna',      insuranceNumber: 'AE-45612', status: 'active', registeredAt: '2023-02-14T10:30:00Z', assignedDoctorId: 'staff-3' },
  { id: 'pat-3',  patientNumber: 'PT-0003', firstName: 'Michael',   lastName: 'Brown',     email: 'michael.brown@email.com',   phone: '+1-555-1005', dateOfBirth: '2015-11-05', gender: 'male',   bloodType: 'O+',      address: '789 Pine Rd',        city: 'Lakewood',    emergencyContactName: 'Sandra Brown',     emergencyContactPhone: '+1-555-1006', allergies: [],                          chronicConditions: ['Asthma'],                  insuranceProvider: 'United',     insuranceNumber: 'UH-33421', status: 'active', registeredAt: '2023-03-05T08:15:00Z', assignedDoctorId: 'staff-4' },
  { id: 'pat-4',  patientNumber: 'PT-0004', firstName: 'Sophia',    lastName: 'Davis',     email: 'sophia.davis@email.com',    phone: '+1-555-1007', dateOfBirth: '1965-09-30', gender: 'female', bloodType: 'AB-',     address: '321 Elm Blvd',       city: 'Greenville',  emergencyContactName: 'Robert Davis',     emergencyContactPhone: '+1-555-1008', allergies: ['Aspirin', 'Ibuprofen'],    chronicConditions: ['Osteoarthritis'],          insuranceProvider: 'Cigna',      insuranceNumber: 'CG-77891', status: 'active', registeredAt: '2023-01-22T14:00:00Z', assignedDoctorId: 'staff-5' },
  { id: 'pat-5',  patientNumber: 'PT-0005', firstName: 'James',     lastName: 'Johnson',   email: 'james.j@email.com',         phone: '+1-555-1009', dateOfBirth: '1982-12-18', gender: 'male',   bloodType: 'O-',      address: '654 Cedar Ln',       city: 'Fairview',    emergencyContactName: 'Patricia Johnson',  emergencyContactPhone: '+1-555-1010', allergies: [],                          chronicConditions: [],                          insuranceProvider: undefined,    insuranceNumber: undefined,   status: 'active', registeredAt: '2023-04-11T11:45:00Z', assignedDoctorId: 'staff-6' },
  { id: 'pat-6',  patientNumber: 'PT-0006', firstName: 'Isabella',  lastName: 'Garcia',    email: 'isabella.g@email.com',      phone: '+1-555-1011', dateOfBirth: '1995-03-27', gender: 'female', bloodType: 'A-',      address: '987 Birch St',       city: 'Maplewood',   emergencyContactName: 'Carlos Garcia',    emergencyContactPhone: '+1-555-1012', allergies: ['Latex'],                   chronicConditions: ['Hypothyroidism'],          insuranceProvider: 'BlueCross',  insuranceNumber: 'BC-12345', status: 'active', registeredAt: '2023-05-02T09:30:00Z', assignedDoctorId: 'staff-7' },
  { id: 'pat-7',  patientNumber: 'PT-0007', firstName: 'William',   lastName: 'Martinez',  email: 'william.m@email.com',       phone: '+1-555-1013', dateOfBirth: '1958-08-14', gender: 'male',   bloodType: 'B-',      address: '147 Walnut Ave',     city: 'Springfield', emergencyContactName: 'Rosa Martinez',    emergencyContactPhone: '+1-555-1014', allergies: [],                          chronicConditions: ['COPD', 'Hypertension'],    insuranceProvider: 'Medicare',   insuranceNumber: 'MC-99812', status: 'active', registeredAt: '2022-11-30T13:00:00Z', assignedDoctorId: 'staff-8' },
  { id: 'pat-8',  patientNumber: 'PT-0008', firstName: 'Olivia',    lastName: 'Taylor',    email: 'olivia.t@email.com',        phone: '+1-555-1015', dateOfBirth: '2000-01-09', gender: 'female', bloodType: 'AB+',     address: '258 Spruce Dr',      city: 'Riverside',   emergencyContactName: 'James Taylor',     emergencyContactPhone: '+1-555-1016', allergies: ['Shellfish'],               chronicConditions: ['Eczema'],                  insuranceProvider: 'Aetna',      insuranceNumber: 'AE-66543', status: 'active', registeredAt: '2024-01-08T10:00:00Z', assignedDoctorId: 'staff-9' },
  { id: 'pat-9',  patientNumber: 'PT-0009', firstName: 'Benjamin',  lastName: 'Lee',       email: 'ben.lee@email.com',         phone: '+1-555-1017', dateOfBirth: '1973-06-22', gender: 'male',   bloodType: 'O+',      address: '369 Hickory Ln',     city: 'Lakewood',    emergencyContactName: 'Jenny Lee',        emergencyContactPhone: '+1-555-1018', allergies: ['Codeine'],                 chronicConditions: ['Coronary Artery Disease'], insuranceProvider: 'United',     insuranceNumber: 'UH-55234', status: 'active', registeredAt: '2022-08-19T08:30:00Z', assignedDoctorId: 'staff-2' },
  { id: 'pat-10', patientNumber: 'PT-0010', firstName: 'Ava',       lastName: 'Thomas',    email: 'ava.thomas@email.com',      phone: '+1-555-1019', dateOfBirth: '1987-02-03', gender: 'female', bloodType: 'A+',      address: '741 Poplar St',      city: 'Greenville',  emergencyContactName: 'Mark Thomas',      emergencyContactPhone: '+1-555-1020', allergies: [],                          chronicConditions: ['Epilepsy'],                insuranceProvider: 'Cigna',      insuranceNumber: 'CG-44321', status: 'active', registeredAt: '2023-06-17T15:00:00Z', assignedDoctorId: 'staff-3' },
  { id: 'pat-11', patientNumber: 'PT-0011', firstName: 'Lucas',     lastName: 'Jackson',   email: 'lucas.j@email.com',         phone: '+1-555-1021', dateOfBirth: '2010-10-15', gender: 'male',   bloodType: 'B+',      address: '852 Magnolia Blvd',  city: 'Fairview',    emergencyContactName: 'Sara Jackson',     emergencyContactPhone: '+1-555-1022', allergies: ['Peanuts'],                 chronicConditions: [],                          insuranceProvider: 'BlueCross',  insuranceNumber: 'BC-22111', status: 'active', registeredAt: '2024-02-20T09:00:00Z', assignedDoctorId: 'staff-7' },
  { id: 'pat-12', patientNumber: 'PT-0012', firstName: 'Mia',       lastName: 'White',     email: 'mia.white@email.com',       phone: '+1-555-1023', dateOfBirth: '1993-05-08', gender: 'female', bloodType: 'O+',      address: '963 Chestnut Ave',   city: 'Maplewood',   emergencyContactName: 'Daniel White',     emergencyContactPhone: '+1-555-1024', allergies: [],                          chronicConditions: ['PCOS'],                    insuranceProvider: 'United',     insuranceNumber: 'UH-88765', status: 'active', registeredAt: '2024-03-01T11:00:00Z', assignedDoctorId: 'staff-8' },
  { id: 'pat-13', patientNumber: 'PT-0013', firstName: 'Henry',     lastName: 'Harris',    email: 'henry.h@email.com',         phone: '+1-555-1025', dateOfBirth: '1945-12-01', gender: 'male',   bloodType: 'A-',      address: '147 Sycamore Rd',    city: 'Springfield', emergencyContactName: 'Dorothy Harris',   emergencyContactPhone: '+1-555-1026', allergies: ['Warfarin'],                chronicConditions: ['Atrial Fibrillation', 'Heart Failure'], insuranceProvider: 'Medicare', insuranceNumber: 'MC-44321', status: 'active', registeredAt: '2022-05-10T10:00:00Z', assignedDoctorId: 'staff-2' },
  { id: 'pat-14', patientNumber: 'PT-0014', firstName: 'Charlotte', lastName: 'Martin',    email: 'charlotte.m@email.com',     phone: '+1-555-1027', dateOfBirth: '2018-07-19', gender: 'female', bloodType: 'B+',      address: '258 Dogwood Ln',     city: 'Riverside',   emergencyContactName: 'Kevin Martin',     emergencyContactPhone: '+1-555-1028', allergies: [],                          chronicConditions: [],                          insuranceProvider: 'Aetna',      insuranceNumber: 'AE-99876', status: 'active', registeredAt: '2024-01-25T14:30:00Z', assignedDoctorId: 'staff-4' },
  { id: 'pat-15', patientNumber: 'PT-0015', firstName: 'Alexander', lastName: 'Thompson',  email: 'alex.t@email.com',          phone: '+1-555-1029', dateOfBirth: '1969-09-04', gender: 'male',   bloodType: 'O-',      address: '369 Redwood Ave',    city: 'Lakewood',    emergencyContactName: 'Susan Thompson',   emergencyContactPhone: '+1-555-1030', allergies: ['NSAIDs'],                  chronicConditions: ['Psoriasis'],               insuranceProvider: 'Cigna',      insuranceNumber: 'CG-11234', status: 'active', registeredAt: '2023-09-12T08:00:00Z', assignedDoctorId: 'staff-9' },
  { id: 'pat-16', patientNumber: 'PT-0016', firstName: 'Amelia',    lastName: 'Garcia',    email: 'amelia.g@email.com',        phone: '+1-555-1031', dateOfBirth: '2001-04-16', gender: 'female', bloodType: 'AB+',     address: '741 Aspen St',       city: 'Greenville',  emergencyContactName: 'Miguel Garcia',    emergencyContactPhone: '+1-555-1032', allergies: [],                          chronicConditions: ['Anxiety Disorder'],        insuranceProvider: 'BlueCross',  insuranceNumber: 'BC-55678', status: 'active', registeredAt: '2024-04-03T09:45:00Z', assignedDoctorId: 'staff-7' },
  { id: 'pat-17', patientNumber: 'PT-0017', firstName: 'Ethan',     lastName: 'Moore',     email: 'ethan.m@email.com',         phone: '+1-555-1033', dateOfBirth: '1983-11-29', gender: 'male',   bloodType: 'A+',      address: '852 Willow Dr',      city: 'Fairview',    emergencyContactName: 'Karen Moore',      emergencyContactPhone: '+1-555-1034', allergies: ['Amoxicillin'],             chronicConditions: ['Multiple Sclerosis'],      insuranceProvider: 'United',     insuranceNumber: 'UH-77654', status: 'active', registeredAt: '2023-07-28T13:15:00Z', assignedDoctorId: 'staff-3' },
  { id: 'pat-18', patientNumber: 'PT-0018', firstName: 'Harper',    lastName: 'Walker',    email: 'harper.w@email.com',        phone: '+1-555-1035', dateOfBirth: '1996-02-14', gender: 'female', bloodType: 'B-',      address: '963 Hawthorn Blvd',  city: 'Maplewood',   emergencyContactName: 'Brian Walker',     emergencyContactPhone: '+1-555-1036', allergies: [],                          chronicConditions: [],                          insuranceProvider: undefined,    insuranceNumber: undefined,   status: 'active', registeredAt: '2024-05-01T10:30:00Z', assignedDoctorId: 'staff-6' },
  { id: 'pat-19', patientNumber: 'PT-0019', firstName: 'Daniel',    lastName: 'Hall',      email: 'daniel.h@email.com',        phone: '+1-555-1037', dateOfBirth: '1971-08-07', gender: 'male',   bloodType: 'O+',      address: '147 Juniper Ln',     city: 'Springfield', emergencyContactName: 'Linda Hall',       emergencyContactPhone: '+1-555-1038', allergies: ['Sulfa'],                   chronicConditions: ['Gout', 'Hypertension'],    insuranceProvider: 'Cigna',      insuranceNumber: 'CG-33456', status: 'active', registeredAt: '2023-10-05T08:30:00Z', assignedDoctorId: 'staff-5' },
  { id: 'pat-20', patientNumber: 'PT-0020', firstName: 'Sofia',     lastName: 'Young',     email: 'sofia.y@email.com',         phone: '+1-555-1039', dateOfBirth: '1988-06-11', gender: 'female', bloodType: 'A-',      address: '258 Laurel Ave',     city: 'Riverside',   emergencyContactName: 'Mark Young',       emergencyContactPhone: '+1-555-1040', allergies: [],                          chronicConditions: ['Endometriosis'],           insuranceProvider: 'Aetna',      insuranceNumber: 'AE-22345', status: 'active', registeredAt: '2024-02-10T11:30:00Z', assignedDoctorId: 'staff-8' },
];

// ─── Rooms ────────────────────────────────────────────────────────────────────
const rooms: Room[] = [
  { id: 'room-1',  roomNumber: '101', type: 'general',      floor: 1, departmentId: 'dept-5', capacity: 4,  occupiedBeds: 2,  status: 'available' },
  { id: 'room-2',  roomNumber: '102', type: 'emergency',    floor: 1, departmentId: 'dept-5', capacity: 2,  occupiedBeds: 2,  status: 'full' },
  { id: 'room-3',  roomNumber: '103', type: 'icu',          floor: 1, departmentId: 'dept-5', capacity: 4,  occupiedBeds: 1,  status: 'available' },
  { id: 'room-4',  roomNumber: '201', type: 'general',      floor: 2, departmentId: 'dept-6', capacity: 6,  occupiedBeds: 4,  status: 'available' },
  { id: 'room-5',  roomNumber: '202', type: 'consultation', floor: 2, departmentId: 'dept-6', capacity: 1,  occupiedBeds: 0,  status: 'available' },
  { id: 'room-6',  roomNumber: '203', type: 'general',      floor: 2, departmentId: 'dept-3', capacity: 6,  occupiedBeds: 3,  status: 'available' },
  { id: 'room-7',  roomNumber: '204', type: 'private',      floor: 2, departmentId: 'dept-3', capacity: 1,  occupiedBeds: 1,  status: 'full' },
  { id: 'room-8',  roomNumber: '205', type: 'consultation', floor: 2, departmentId: 'dept-8', capacity: 1,  occupiedBeds: 0,  status: 'available' },
  { id: 'room-9',  roomNumber: '301', type: 'general',      floor: 3, departmentId: 'dept-1', capacity: 4,  occupiedBeds: 4,  status: 'full' },
  { id: 'room-10', roomNumber: '302', type: 'icu',          floor: 3, departmentId: 'dept-1', capacity: 2,  occupiedBeds: 1,  status: 'available' },
  { id: 'room-11', roomNumber: '303', type: 'operation',    floor: 3, departmentId: 'dept-4', capacity: 1,  occupiedBeds: 0,  status: 'available' },
  { id: 'room-12', roomNumber: '304', type: 'general',      floor: 3, departmentId: 'dept-4', capacity: 4,  occupiedBeds: 2,  status: 'available' },
  { id: 'room-13', roomNumber: '401', type: 'general',      floor: 4, departmentId: 'dept-2', capacity: 4,  occupiedBeds: 3,  status: 'available' },
  { id: 'room-14', roomNumber: '402', type: 'private',      floor: 4, departmentId: 'dept-7', capacity: 1,  occupiedBeds: 1,  status: 'full' },
  { id: 'room-15', roomNumber: '403', type: 'general',      floor: 4, departmentId: 'dept-7', capacity: 4,  occupiedBeds: 1,  status: 'available' },
  { id: 'room-16', roomNumber: '106', type: 'maintenance',  floor: 1, departmentId: 'dept-5', capacity: 4,  occupiedBeds: 0,  status: 'maintenance' },
];

// ─── Appointments ─────────────────────────────────────────────────────────────
// Today = 2026-05-18
const appointments: Appointment[] = [
  // Today's appointments
  { id: 'apt-1',  appointmentNumber: 'APT-0001', patientId: 'pat-1',  doctorId: 'staff-2', departmentId: 'dept-1', date: '2026-05-18', time: '08:30', duration: 30, type: 'follow_up',    status: 'completed',   reason: 'Blood pressure follow-up',            notes: 'BP stable, continue current medication',               createdAt: '2026-05-01T09:00:00Z', updatedAt: '2026-05-18T09:00:00Z' },
  { id: 'apt-2',  appointmentNumber: 'APT-0002', patientId: 'pat-9',  doctorId: 'staff-2', departmentId: 'dept-1', date: '2026-05-18', time: '09:00', duration: 45, type: 'consultation', status: 'completed',   reason: 'Chest pain evaluation',               notes: 'ECG ordered, referral for stress test',                createdAt: '2026-05-10T10:00:00Z', updatedAt: '2026-05-18T09:45:00Z' },
  { id: 'apt-3',  appointmentNumber: 'APT-0003', patientId: 'pat-13', doctorId: 'staff-2', departmentId: 'dept-1', date: '2026-05-18', time: '10:00', duration: 45, type: 'check_up',     status: 'in_progress', reason: 'Monthly cardiac check',               notes: '',                                                     createdAt: '2026-05-05T08:00:00Z', updatedAt: '2026-05-18T10:05:00Z' },
  { id: 'apt-4',  appointmentNumber: 'APT-0004', patientId: 'pat-2',  doctorId: 'staff-3', departmentId: 'dept-2', date: '2026-05-18', time: '09:30', duration: 60, type: 'consultation', status: 'completed',   reason: 'Migraine management review',          notes: 'New preventive medication prescribed',                 createdAt: '2026-05-08T14:00:00Z', updatedAt: '2026-05-18T10:30:00Z' },
  { id: 'apt-5',  appointmentNumber: 'APT-0005', patientId: 'pat-10', doctorId: 'staff-3', departmentId: 'dept-2', date: '2026-05-18', time: '11:00', duration: 45, type: 'follow_up',    status: 'scheduled',   reason: 'Epilepsy medication review',          notes: '',                                                     createdAt: '2026-05-12T09:00:00Z', updatedAt: '2026-05-12T09:00:00Z' },
  { id: 'apt-6',  appointmentNumber: 'APT-0006', patientId: 'pat-17', doctorId: 'staff-3', departmentId: 'dept-2', date: '2026-05-18', time: '14:00', duration: 60, type: 'consultation', status: 'scheduled',   reason: 'MS symptom assessment',               notes: '',                                                     createdAt: '2026-05-14T11:00:00Z', updatedAt: '2026-05-14T11:00:00Z' },
  { id: 'apt-7',  appointmentNumber: 'APT-0007', patientId: 'pat-3',  doctorId: 'staff-4', departmentId: 'dept-3', date: '2026-05-18', time: '08:00', duration: 30, type: 'check_up',     status: 'completed',   reason: 'Asthma routine check',                notes: 'Good control, continue inhaler',                       createdAt: '2026-05-07T10:00:00Z', updatedAt: '2026-05-18T08:30:00Z' },
  { id: 'apt-8',  appointmentNumber: 'APT-0008', patientId: 'pat-14', doctorId: 'staff-4', departmentId: 'dept-3', date: '2026-05-18', time: '10:30', duration: 30, type: 'check_up',     status: 'scheduled',   reason: '18-month developmental check',        notes: '',                                                     createdAt: '2026-05-10T09:00:00Z', updatedAt: '2026-05-10T09:00:00Z' },
  { id: 'apt-9',  appointmentNumber: 'APT-0009', patientId: 'pat-6',  doctorId: 'staff-7', departmentId: 'dept-6', date: '2026-05-18', time: '09:00', duration: 30, type: 'consultation', status: 'confirmed',   reason: 'Thyroid medication adjustment',        notes: '',                                                     createdAt: '2026-05-13T08:00:00Z', updatedAt: '2026-05-15T10:00:00Z' },
  { id: 'apt-10', appointmentNumber: 'APT-0010', patientId: 'pat-11', doctorId: 'staff-7', departmentId: 'dept-6', date: '2026-05-18', time: '11:30', duration: 30, type: 'consultation', status: 'scheduled',   reason: 'Seasonal allergy consultation',        notes: '',                                                     createdAt: '2026-05-14T14:00:00Z', updatedAt: '2026-05-14T14:00:00Z' },
  { id: 'apt-11', appointmentNumber: 'APT-0011', patientId: 'pat-16', doctorId: 'staff-7', departmentId: 'dept-6', date: '2026-05-18', time: '15:00', duration: 30, type: 'follow_up',    status: 'scheduled',   reason: 'Anxiety disorder follow-up',           notes: '',                                                     createdAt: '2026-05-15T09:00:00Z', updatedAt: '2026-05-15T09:00:00Z' },
  { id: 'apt-12', appointmentNumber: 'APT-0012', patientId: 'pat-5',  doctorId: 'staff-6', departmentId: 'dept-5', date: '2026-05-18', time: '07:30', duration: 60, type: 'emergency',    status: 'completed',   reason: 'Acute abdominal pain',                notes: 'Appendix ruled out, gastritis diagnosed',              createdAt: '2026-05-18T07:20:00Z', updatedAt: '2026-05-18T08:35:00Z' },
  { id: 'apt-13', appointmentNumber: 'APT-0013', patientId: 'pat-18', doctorId: 'staff-6', departmentId: 'dept-5', date: '2026-05-18', time: '13:00', duration: 30, type: 'consultation', status: 'scheduled',   reason: 'Laceration evaluation',               notes: '',                                                     createdAt: '2026-05-18T12:50:00Z', updatedAt: '2026-05-18T12:50:00Z' },
  // Future appointments
  { id: 'apt-14', appointmentNumber: 'APT-0014', patientId: 'pat-4',  doctorId: 'staff-5', departmentId: 'dept-4', date: '2026-05-20', time: '09:00', duration: 45, type: 'follow_up',    status: 'confirmed',   reason: 'Post-surgery knee check',             notes: '',                                                     createdAt: '2026-05-16T10:00:00Z', updatedAt: '2026-05-17T09:00:00Z' },
  { id: 'apt-15', appointmentNumber: 'APT-0015', patientId: 'pat-19', doctorId: 'staff-5', departmentId: 'dept-4', date: '2026-05-21', time: '10:00', duration: 30, type: 'consultation', status: 'scheduled',   reason: 'Hip pain assessment',                 notes: '',                                                     createdAt: '2026-05-15T11:00:00Z', updatedAt: '2026-05-15T11:00:00Z' },
  { id: 'apt-16', appointmentNumber: 'APT-0016', patientId: 'pat-7',  doctorId: 'staff-8', departmentId: 'dept-7', date: '2026-05-22', time: '11:00', duration: 45, type: 'check_up',     status: 'scheduled',   reason: 'Annual gynecology check',             notes: '',                                                     createdAt: '2026-05-10T08:00:00Z', updatedAt: '2026-05-10T08:00:00Z' },
  { id: 'apt-17', appointmentNumber: 'APT-0017', patientId: 'pat-12', doctorId: 'staff-8', departmentId: 'dept-7', date: '2026-05-23', time: '14:00', duration: 30, type: 'follow_up',    status: 'scheduled',   reason: 'PCOS hormone review',                 notes: '',                                                     createdAt: '2026-05-14T09:00:00Z', updatedAt: '2026-05-14T09:00:00Z' },
  { id: 'apt-18', appointmentNumber: 'APT-0018', patientId: 'pat-20', doctorId: 'staff-8', departmentId: 'dept-7', date: '2026-05-25', time: '10:00', duration: 45, type: 'consultation', status: 'scheduled',   reason: 'Endometriosis pain management',       notes: '',                                                     createdAt: '2026-05-15T10:00:00Z', updatedAt: '2026-05-15T10:00:00Z' },
  { id: 'apt-19', appointmentNumber: 'APT-0019', patientId: 'pat-1',  doctorId: 'staff-2', departmentId: 'dept-1', date: '2026-06-02', time: '09:00', duration: 30, type: 'follow_up',    status: 'scheduled',   reason: 'Diabetes quarterly review',           notes: '',                                                     createdAt: '2026-05-17T14:00:00Z', updatedAt: '2026-05-17T14:00:00Z' },
  { id: 'apt-20', appointmentNumber: 'APT-0020', patientId: 'pat-8',  doctorId: 'staff-9', departmentId: 'dept-8', date: '2026-06-05', time: '15:00', duration: 30, type: 'follow_up',    status: 'scheduled',   reason: 'Eczema treatment follow-up',          notes: '',                                                     createdAt: '2026-05-18T08:00:00Z', updatedAt: '2026-05-18T08:00:00Z' },
  // Past appointments
  { id: 'apt-21', appointmentNumber: 'APT-0021', patientId: 'pat-1',  doctorId: 'staff-2', departmentId: 'dept-1', date: '2026-04-15', time: '09:00', duration: 30, type: 'follow_up',    status: 'completed',   reason: 'Blood pressure check',                notes: 'BP 140/90, adjusted medication dosage', createdAt: '2026-04-01T09:00:00Z', updatedAt: '2026-04-15T09:30:00Z' },
  { id: 'apt-22', appointmentNumber: 'APT-0022', patientId: 'pat-2',  doctorId: 'staff-3', departmentId: 'dept-2', date: '2026-04-20', time: '10:00', duration: 60, type: 'check_up',     status: 'completed',   reason: 'Neurology annual check',              notes: 'MRI results reviewed, stable',         createdAt: '2026-04-10T08:00:00Z', updatedAt: '2026-04-20T11:00:00Z' },
  { id: 'apt-23', appointmentNumber: 'APT-0023', patientId: 'pat-6',  doctorId: 'staff-7', departmentId: 'dept-6', date: '2026-05-05', time: '14:00', duration: 30, type: 'consultation', status: 'no_show',     reason: 'General consultation',                cancelledReason: 'Patient did not show',       createdAt: '2026-04-28T09:00:00Z', updatedAt: '2026-05-05T14:30:00Z' },
  { id: 'apt-24', appointmentNumber: 'APT-0024', patientId: 'pat-9',  doctorId: 'staff-2', departmentId: 'dept-1', date: '2026-05-10', time: '09:00', duration: 45, type: 'check_up',     status: 'completed',   reason: 'Cardiac enzyme test review',          notes: 'Troponin levels normal',               createdAt: '2026-05-01T09:00:00Z', updatedAt: '2026-05-10T09:50:00Z' },
  { id: 'apt-25', appointmentNumber: 'APT-0025', patientId: 'pat-11', doctorId: 'staff-7', departmentId: 'dept-6', date: '2026-05-12', time: '11:00', duration: 30, type: 'consultation', status: 'cancelled',   reason: 'Allergy testing',                     cancelledReason: 'Doctor unavailable',        createdAt: '2026-05-06T10:00:00Z', updatedAt: '2026-05-11T08:00:00Z' },
];

// ─── Prescriptions ────────────────────────────────────────────────────────────
const prescriptions: Prescription[] = [
  { id: 'rx-1', prescriptionNumber: 'RX-0001', patientId: 'pat-1',  doctorId: 'staff-2', appointmentId: 'apt-21', diagnosis: 'Hypertension', items: [{ medicine: 'Amlodipine', dosage: '5mg', frequency: 'Once daily', duration: '90 days', instructions: 'Take in the morning' }, { medicine: 'Metformin', dosage: '500mg', frequency: 'Twice daily', duration: '90 days', instructions: 'Take with meals' }], status: 'active', createdAt: '2026-04-15T09:30:00Z', expiresAt: '2026-07-14T00:00:00Z' },
  { id: 'rx-2', prescriptionNumber: 'RX-0002', patientId: 'pat-2',  doctorId: 'staff-3', appointmentId: 'apt-4',  diagnosis: 'Chronic Migraine', items: [{ medicine: 'Topiramate', dosage: '25mg', frequency: 'Once at bedtime', duration: '60 days', instructions: 'Gradually increase dose' }, { medicine: 'Sumatriptan', dosage: '50mg', frequency: 'As needed (max 2/day)', duration: '30 days', instructions: 'Take at migraine onset' }], status: 'active', createdAt: '2026-05-18T10:30:00Z', expiresAt: '2026-07-17T00:00:00Z' },
  { id: 'rx-3', prescriptionNumber: 'RX-0003', patientId: 'pat-9',  doctorId: 'staff-2', appointmentId: 'apt-24', diagnosis: 'Coronary Artery Disease', items: [{ medicine: 'Aspirin', dosage: '81mg', frequency: 'Once daily', duration: '180 days', instructions: 'Take with food' }, { medicine: 'Atorvastatin', dosage: '40mg', frequency: 'Once at bedtime', duration: '180 days' }, { medicine: 'Metoprolol', dosage: '25mg', frequency: 'Twice daily', duration: '180 days' }], status: 'active', createdAt: '2026-05-10T09:50:00Z', expiresAt: '2026-11-06T00:00:00Z' },
  { id: 'rx-4', prescriptionNumber: 'RX-0004', patientId: 'pat-6',  doctorId: 'staff-7', appointmentId: 'apt-9',  diagnosis: 'Hypothyroidism', items: [{ medicine: 'Levothyroxine', dosage: '75mcg', frequency: 'Once daily', duration: '90 days', instructions: 'Take 30 minutes before breakfast' }], status: 'active', createdAt: '2026-05-18T09:30:00Z', expiresAt: '2026-08-16T00:00:00Z' },
  { id: 'rx-5', prescriptionNumber: 'RX-0005', patientId: 'pat-13', doctorId: 'staff-2', appointmentId: 'apt-3',  diagnosis: 'Heart Failure', items: [{ medicine: 'Furosemide', dosage: '40mg', frequency: 'Once daily', duration: '30 days', instructions: 'Monitor weight daily' }, { medicine: 'Carvedilol', dosage: '6.25mg', frequency: 'Twice daily', duration: '30 days', instructions: 'Take with food' }, { medicine: 'Lisinopril', dosage: '5mg', frequency: 'Once daily', duration: '30 days' }], status: 'active', createdAt: '2026-05-18T10:45:00Z', expiresAt: '2026-06-17T00:00:00Z' },
  { id: 'rx-6', prescriptionNumber: 'RX-0006', patientId: 'pat-3',  doctorId: 'staff-4', appointmentId: 'apt-7',  diagnosis: 'Asthma', items: [{ medicine: 'Salbutamol Inhaler', dosage: '100mcg', frequency: '2 puffs as needed', duration: '90 days', instructions: 'Shake well before use' }, { medicine: 'Fluticasone Inhaler', dosage: '100mcg', frequency: '2 puffs twice daily', duration: '90 days', instructions: 'Rinse mouth after use' }], status: 'active', createdAt: '2026-05-18T08:30:00Z', expiresAt: '2026-08-16T00:00:00Z' },
  { id: 'rx-7', prescriptionNumber: 'RX-0007', patientId: 'pat-7',  doctorId: 'staff-8', appointmentId: 'apt-16', diagnosis: 'COPD', items: [{ medicine: 'Tiotropium Inhaler', dosage: '18mcg', frequency: 'Once daily', duration: '90 days', instructions: 'Use HandiHaler device' }, { medicine: 'Prednisolone', dosage: '5mg', frequency: 'Once daily for 5 days', duration: '5 days', instructions: 'Take with food' }], status: 'completed', createdAt: '2026-04-01T10:00:00Z', expiresAt: '2026-05-01T00:00:00Z' },
];

// ─── Lab Orders ───────────────────────────────────────────────────────────────
const labOrders: LabOrder[] = [
  { id: 'lab-1', labNumber: 'LAB-0001', patientId: 'pat-1',  doctorId: 'staff-2', appointmentId: 'apt-1',  tests: ['HbA1c', 'Fasting Glucose', 'Lipid Panel'], status: 'completed', priority: 'routine', orderedAt: '2026-05-18T08:45:00Z', completedAt: '2026-05-18T14:00:00Z', results: [{ testName: 'HbA1c', value: '7.2', unit: '%', referenceRange: '< 5.7', flag: 'abnormal' }, { testName: 'Fasting Glucose', value: '132', unit: 'mg/dL', referenceRange: '70-100', flag: 'abnormal' }, { testName: 'Total Cholesterol', value: '188', unit: 'mg/dL', referenceRange: '< 200', flag: 'normal' }] },
  { id: 'lab-2', labNumber: 'LAB-0002', patientId: 'pat-9',  doctorId: 'staff-2', appointmentId: 'apt-2',  tests: ['Troponin I', 'CK-MB', 'BNP', 'ECG'], status: 'completed', priority: 'urgent', orderedAt: '2026-05-18T09:10:00Z', completedAt: '2026-05-18T11:00:00Z', results: [{ testName: 'Troponin I', value: '0.02', unit: 'ng/mL', referenceRange: '< 0.04', flag: 'normal' }, { testName: 'CK-MB', value: '3.1', unit: 'ng/mL', referenceRange: '< 5.0', flag: 'normal' }, { testName: 'BNP', value: '95', unit: 'pg/mL', referenceRange: '< 100', flag: 'normal' }] },
  { id: 'lab-3', labNumber: 'LAB-0003', patientId: 'pat-2',  doctorId: 'staff-3', appointmentId: 'apt-22', tests: ['MRI Brain', 'CBC', 'Electrolytes'], status: 'completed', priority: 'routine', orderedAt: '2026-04-20T11:00:00Z', completedAt: '2026-04-22T16:00:00Z', results: [{ testName: 'MRI Brain', value: 'No acute intracranial abnormality', unit: '', referenceRange: 'Normal', flag: 'normal' }, { testName: 'WBC', value: '7.2', unit: 'K/uL', referenceRange: '4.5-11.0', flag: 'normal' }] },
  { id: 'lab-4', labNumber: 'LAB-0004', patientId: 'pat-5',  doctorId: 'staff-6', appointmentId: 'apt-12', tests: ['CBC', 'CMP', 'Lipase', 'Amylase', 'Urinalysis'], status: 'completed', priority: 'stat', orderedAt: '2026-05-18T07:30:00Z', completedAt: '2026-05-18T09:00:00Z', results: [{ testName: 'WBC', value: '11.8', unit: 'K/uL', referenceRange: '4.5-11.0', flag: 'abnormal' }, { testName: 'Lipase', value: '45', unit: 'U/L', referenceRange: '10-140', flag: 'normal' }, { testName: 'Amylase', value: '88', unit: 'U/L', referenceRange: '30-110', flag: 'normal' }] },
  { id: 'lab-5', labNumber: 'LAB-0005', patientId: 'pat-10', doctorId: 'staff-3', appointmentId: 'apt-5',  tests: ['Serum Valproate Level', 'CBC', 'LFT'], status: 'ordered', priority: 'routine', orderedAt: '2026-05-18T11:10:00Z', completedAt: undefined },
  { id: 'lab-6', labNumber: 'LAB-0006', patientId: 'pat-13', doctorId: 'staff-2', appointmentId: 'apt-3',  tests: ['BNP', 'Creatinine', 'Electrolytes', 'Chest X-Ray'], status: 'processing', priority: 'urgent', orderedAt: '2026-05-18T10:20:00Z', completedAt: undefined },
  { id: 'lab-7', labNumber: 'LAB-0007', patientId: 'pat-6',  doctorId: 'staff-7', appointmentId: 'apt-9',  tests: ['TSH', 'Free T4', 'Free T3'], status: 'completed', priority: 'routine', orderedAt: '2026-05-18T09:30:00Z', completedAt: '2026-05-18T13:00:00Z', results: [{ testName: 'TSH', value: '6.8', unit: 'mIU/L', referenceRange: '0.4-4.0', flag: 'abnormal' }, { testName: 'Free T4', value: '0.9', unit: 'ng/dL', referenceRange: '0.8-1.8', flag: 'normal' }] },
];

// ─── Invoices ─────────────────────────────────────────────────────────────────
const invoices: Invoice[] = [
  { id: 'inv-1', invoiceNumber: 'INV-0001', patientId: 'pat-1',  appointmentId: 'apt-21', items: [{ description: 'Consultation Fee', quantity: 1, unitPrice: 150, total: 150 }, { description: 'Blood Tests (HbA1c, Glucose, Lipids)', quantity: 1, unitPrice: 120, total: 120 }], subtotal: 270, tax: 0, discount: 0, total: 270, amountPaid: 270, status: 'paid',    paymentMethod: 'card',      createdAt: '2026-04-15T09:35:00Z', dueDate: '2026-04-30', paidAt: '2026-04-15T09:40:00Z' },
  { id: 'inv-2', invoiceNumber: 'INV-0002', patientId: 'pat-9',  appointmentId: 'apt-24', items: [{ description: 'Cardiology Consultation', quantity: 1, unitPrice: 250, total: 250 }, { description: 'Cardiac Enzyme Panel', quantity: 1, unitPrice: 200, total: 200 }, { description: 'ECG', quantity: 1, unitPrice: 80, total: 80 }], subtotal: 530, tax: 0, discount: 50, total: 480, amountPaid: 480, status: 'paid',    paymentMethod: 'insurance', createdAt: '2026-05-10T10:00:00Z', dueDate: '2026-05-25', paidAt: '2026-05-10T10:05:00Z' },
  { id: 'inv-3', invoiceNumber: 'INV-0003', patientId: 'pat-2',  appointmentId: 'apt-22', items: [{ description: 'Neurology Consultation', quantity: 1, unitPrice: 300, total: 300 }, { description: 'MRI Brain', quantity: 1, unitPrice: 850, total: 850 }], subtotal: 1150, tax: 0, discount: 0, total: 1150, amountPaid: 500, status: 'partially_paid', paymentMethod: 'insurance', createdAt: '2026-04-20T11:05:00Z', dueDate: '2026-05-05' },
  { id: 'inv-4', invoiceNumber: 'INV-0004', patientId: 'pat-5',  appointmentId: 'apt-12', items: [{ description: 'Emergency Consultation', quantity: 1, unitPrice: 450, total: 450 }, { description: 'Emergency Lab Panel', quantity: 1, unitPrice: 280, total: 280 }], subtotal: 730, tax: 0, discount: 0, total: 730, amountPaid: 0, status: 'pending',         createdAt: '2026-05-18T08:40:00Z', dueDate: '2026-06-02' },
  { id: 'inv-5', invoiceNumber: 'INV-0005', patientId: 'pat-13', appointmentId: 'apt-3',  items: [{ description: 'Cardiology Consultation', quantity: 1, unitPrice: 250, total: 250 }, { description: 'BNP & Lab Tests', quantity: 1, unitPrice: 180, total: 180 }, { description: 'Chest X-Ray', quantity: 1, unitPrice: 120, total: 120 }], subtotal: 550, tax: 0, discount: 0, total: 550, amountPaid: 0, status: 'pending',  createdAt: '2026-05-18T10:50:00Z', dueDate: '2026-06-02' },
  { id: 'inv-6', invoiceNumber: 'INV-0006', patientId: 'pat-3',  appointmentId: 'apt-7',  items: [{ description: 'Pediatrics Consultation', quantity: 1, unitPrice: 180, total: 180 }, { description: 'Pulmonary Function Test', quantity: 1, unitPrice: 95, total: 95 }], subtotal: 275, tax: 0, discount: 0, total: 275, amountPaid: 275, status: 'paid', paymentMethod: 'cash', createdAt: '2026-05-18T08:35:00Z', dueDate: '2026-06-02', paidAt: '2026-05-18T08:38:00Z' },
  { id: 'inv-7', invoiceNumber: 'INV-0007', patientId: 'pat-6',  appointmentId: 'apt-9',  items: [{ description: 'General Medicine Consultation', quantity: 1, unitPrice: 150, total: 150 }, { description: 'Thyroid Panel', quantity: 1, unitPrice: 110, total: 110 }], subtotal: 260, tax: 0, discount: 0, total: 260, amountPaid: 0, status: 'pending', createdAt: '2026-05-18T09:35:00Z', dueDate: '2026-06-02' },
  { id: 'inv-8', invoiceNumber: 'INV-0008', patientId: 'pat-7',  appointmentId: undefined, items: [{ description: 'Gynecology Consultation', quantity: 1, unitPrice: 200, total: 200 }], subtotal: 200, tax: 0, discount: 0, total: 200, amountPaid: 0, status: 'overdue', createdAt: '2026-04-01T10:00:00Z', dueDate: '2026-04-16' },
];

// ─── Inventory ────────────────────────────────────────────────────────────────
const inventory: InventoryItem[] = [
  { id: 'inv-item-1',  name: 'Amlodipine 5mg',          category: 'medicine',    unit: 'tablet',  quantity: 2400, minQuantity: 500,  unitPrice: 0.15, supplier: 'PharmaCo Inc',    expiryDate: '2027-06-30', location: 'Pharmacy - Shelf A1', lastRestocked: '2026-04-01' },
  { id: 'inv-item-2',  name: 'Metformin 500mg',          category: 'medicine',    unit: 'tablet',  quantity: 3600, minQuantity: 500,  unitPrice: 0.08, supplier: 'MedSupply Ltd',   expiryDate: '2027-12-31', location: 'Pharmacy - Shelf A2', lastRestocked: '2026-03-15' },
  { id: 'inv-item-3',  name: 'Aspirin 81mg',             category: 'medicine',    unit: 'tablet',  quantity: 450,  minQuantity: 500,  unitPrice: 0.05, supplier: 'PharmaCo Inc',    expiryDate: '2027-08-31', location: 'Pharmacy - Shelf A3', lastRestocked: '2026-02-20' },
  { id: 'inv-item-4',  name: 'Atorvastatin 40mg',        category: 'medicine',    unit: 'tablet',  quantity: 180,  minQuantity: 300,  unitPrice: 0.45, supplier: 'MedSupply Ltd',   expiryDate: '2027-04-30', location: 'Pharmacy - Shelf A4', lastRestocked: '2026-01-10' },
  { id: 'inv-item-5',  name: 'Levothyroxine 75mcg',      category: 'medicine',    unit: 'tablet',  quantity: 900,  minQuantity: 200,  unitPrice: 0.25, supplier: 'PharmaCo Inc',    expiryDate: '2027-10-31', location: 'Pharmacy - Shelf B1', lastRestocked: '2026-05-01' },
  { id: 'inv-item-6',  name: 'Salbutamol Inhaler',       category: 'medicine',    unit: 'unit',    quantity: 85,   minQuantity: 50,   unitPrice: 12.00, supplier: 'RespiCare Ltd',  expiryDate: '2027-03-31', location: 'Pharmacy - Shelf B2', lastRestocked: '2026-04-15' },
  { id: 'inv-item-7',  name: 'Furosemide 40mg',          category: 'medicine',    unit: 'tablet',  quantity: 40,   minQuantity: 200,  unitPrice: 0.12, supplier: 'MedSupply Ltd',   expiryDate: '2027-09-30', location: 'Pharmacy - Shelf B3', lastRestocked: '2025-12-01' },
  { id: 'inv-item-8',  name: 'Surgical Gloves (M)',      category: 'consumable',  unit: 'pair',    quantity: 1200, minQuantity: 300,  unitPrice: 0.45, supplier: 'SafeMed Supplies',expiryDate: undefined,     location: 'Store Room 1',       lastRestocked: '2026-05-10' },
  { id: 'inv-item-9',  name: 'Surgical Masks (N95)',     category: 'consumable',  unit: 'piece',   quantity: 3500, minQuantity: 500,  unitPrice: 1.20, supplier: 'SafeMed Supplies',expiryDate: '2028-01-01', location: 'Store Room 1',        lastRestocked: '2026-05-10' },
  { id: 'inv-item-10', name: 'IV Cannula 20G',           category: 'consumable',  unit: 'piece',   quantity: 220,  minQuantity: 200,  unitPrice: 0.85, supplier: 'MedTech Corp',    expiryDate: '2028-06-30', location: 'Store Room 2',        lastRestocked: '2026-04-20' },
  { id: 'inv-item-11', name: 'Blood Glucose Strips',     category: 'lab_supply',  unit: 'strip',   quantity: 80,   minQuantity: 200,  unitPrice: 0.35, supplier: 'DiagLab Inc',     expiryDate: '2026-10-31', location: 'Lab - Cabinet 1',    lastRestocked: '2026-03-01' },
  { id: 'inv-item-12', name: 'Syringes 5mL',             category: 'consumable',  unit: 'piece',   quantity: 2500, minQuantity: 500,  unitPrice: 0.18, supplier: 'SafeMed Supplies',expiryDate: '2029-01-01', location: 'Store Room 2',        lastRestocked: '2026-05-05' },
  { id: 'inv-item-13', name: 'Digital Thermometer',      category: 'equipment',   unit: 'piece',   quantity: 25,   minQuantity: 10,   unitPrice: 18.00, supplier: 'MedTech Corp',   expiryDate: undefined,     location: 'Nursing Station',    lastRestocked: '2026-01-15' },
  { id: 'inv-item-14', name: 'Blood Pressure Monitor',   category: 'equipment',   unit: 'piece',   quantity: 12,   minQuantity: 5,    unitPrice: 85.00, supplier: 'MedTech Corp',   expiryDate: undefined,     location: 'Nursing Station',    lastRestocked: '2025-11-20' },
  { id: 'inv-item-15', name: 'Pulse Oximeter',           category: 'equipment',   unit: 'piece',   quantity: 18,   minQuantity: 8,    unitPrice: 35.00, supplier: 'DiagLab Inc',    expiryDate: undefined,     location: 'Nursing Station',    lastRestocked: '2026-02-10' },
  { id: 'inv-item-16', name: 'Hydrogen Peroxide 3%',     category: 'medicine',    unit: 'bottle',  quantity: 60,   minQuantity: 30,   unitPrice: 2.50, supplier: 'PharmaCo Inc',    expiryDate: '2027-01-31', location: 'Pharmacy - Shelf C1', lastRestocked: '2026-04-01' },
  { id: 'inv-item-17', name: 'Paracetamol 500mg',        category: 'medicine',    unit: 'tablet',  quantity: 5000, minQuantity: 1000, unitPrice: 0.04, supplier: 'PharmaCo Inc',    expiryDate: '2027-12-31', location: 'Pharmacy - Shelf A5', lastRestocked: '2026-05-01' },
  { id: 'inv-item-18', name: 'Suture Kit (3-0)',         category: 'consumable',  unit: 'kit',     quantity: 45,   minQuantity: 30,   unitPrice: 8.50, supplier: 'SafeMed Supplies',expiryDate: '2028-03-31', location: 'OR Supply Room',      lastRestocked: '2026-03-20' },
];

// ─── Notifications ────────────────────────────────────────────────────────────
const notifications: Notification[] = [
  { id: 'notif-1',  userId: 'staff-2', type: 'appointment',  title: 'New Appointment Scheduled',  message: 'John Anderson has scheduled a follow-up on Jun 2 at 9:00 AM',          read: false, link: '/appointments', createdAt: '2026-05-17T14:05:00Z' },
  { id: 'notif-2',  userId: 'staff-2', type: 'lab_result',   title: 'Lab Results Ready',           message: 'HbA1c results for John Anderson are now available',                    read: false, link: '/reports',      createdAt: '2026-05-18T14:02:00Z' },
  { id: 'notif-3',  userId: 'staff-2', type: 'alert',        title: 'Critical Lab Value',          message: 'High WBC count detected for James Johnson - review immediately',         read: false, link: '/patients',     createdAt: '2026-05-18T09:05:00Z' },
  { id: 'notif-4',  userId: 'staff-3', type: 'appointment',  title: 'Upcoming Appointment',        message: 'Ethan Moore appointment at 2:00 PM today',                             read: true,  link: '/appointments', createdAt: '2026-05-18T08:00:00Z' },
  { id: 'notif-5',  userId: 'staff-1', type: 'system',       title: 'Low Stock Alert',             message: '4 inventory items are below minimum stock levels',                     read: false, link: '/settings',     createdAt: '2026-05-18T07:00:00Z' },
  { id: 'notif-6',  userId: 'staff-1', type: 'billing',      title: 'Overdue Invoice',             message: 'Invoice INV-0008 for William Martinez is overdue',                    read: false, link: '/settings',     createdAt: '2026-05-10T09:00:00Z' },
  { id: 'notif-7',  userId: 'staff-10',type: 'appointment',  title: 'Walk-in Patient',             message: 'Harper Walker has checked in without an appointment',                  read: false, link: '/appointments', createdAt: '2026-05-18T12:48:00Z' },
  { id: 'notif-8',  userId: 'pat-1',   type: 'appointment',  title: 'Appointment Reminder',        message: 'You have a follow-up with Dr. Mitchell on Jun 2 at 9:00 AM',           read: false, link: '/appointments', createdAt: '2026-05-17T09:00:00Z' },
  { id: 'notif-9',  userId: 'pat-1',   type: 'lab_result',   title: 'Lab Results Available',       message: 'Your HbA1c and blood glucose results are ready to view',               read: false, link: '/reports',      createdAt: '2026-05-18T14:05:00Z' },
  { id: 'notif-10', userId: 'pat-2',   type: 'prescription', title: 'Prescription Updated',        message: 'Dr. Chen has issued a new prescription for your migraines',            read: false, link: '/appointments', createdAt: '2026-05-18T10:35:00Z' },
  { id: 'notif-11', userId: 'pat-9',   type: 'billing',      title: 'Invoice Paid',                message: 'Your invoice INV-0002 of $480 has been marked as paid',               read: true,  link: '/appointments', createdAt: '2026-05-10T10:06:00Z' },
  { id: 'notif-12', userId: 'pat-5',   type: 'billing',      title: 'Invoice Generated',           message: 'Invoice INV-0004 for $730 has been generated for your ER visit',      read: false, link: '/appointments', createdAt: '2026-05-18T08:42:00Z' },
];

// ─── Audit Logs ───────────────────────────────────────────────────────────────
const auditLogs: AuditLog[] = [
  { id: 'log-1',  userId: 'staff-10', userRole: 'RECEPTIONIST', action: 'REGISTER_PATIENT',     resource: 'Patient',     resourceId: 'pat-18', details: 'Registered new patient Harper Walker (PT-0018)',               timestamp: '2026-05-01T10:32:00Z' },
  { id: 'log-2',  userId: 'staff-10', userRole: 'RECEPTIONIST', action: 'CREATE_APPOINTMENT',   resource: 'Appointment', resourceId: 'apt-13', details: 'Created walk-in appointment for Harper Walker with Dr. Okafor', timestamp: '2026-05-18T12:52:00Z' },
  { id: 'log-3',  userId: 'staff-2',  userRole: 'DOCTOR',       action: 'CREATE_PRESCRIPTION',  resource: 'Prescription',resourceId: 'rx-5',  details: 'Issued prescription RX-0005 for Henry Harris - Heart Failure',  timestamp: '2026-05-18T10:47:00Z' },
  { id: 'log-4',  userId: 'staff-2',  userRole: 'DOCTOR',       action: 'ORDER_LAB',             resource: 'LabOrder',    resourceId: 'lab-6', details: 'Ordered BNP and Chest X-Ray for Henry Harris',                timestamp: '2026-05-18T10:22:00Z' },
  { id: 'log-5',  userId: 'staff-2',  userRole: 'DOCTOR',       action: 'UPDATE_APPOINTMENT',    resource: 'Appointment', resourceId: 'apt-2', details: 'Updated appointment status to COMPLETED for Benjamin Lee',      timestamp: '2026-05-18T09:47:00Z' },
  { id: 'log-6',  userId: 'staff-3',  userRole: 'DOCTOR',       action: 'CREATE_PRESCRIPTION',  resource: 'Prescription',resourceId: 'rx-2', details: 'Issued prescription RX-0002 for Emma Wilson - Migraine',        timestamp: '2026-05-18T10:32:00Z' },
  { id: 'log-7',  userId: 'staff-1',  userRole: 'ADMIN',        action: 'UPDATE_STAFF',          resource: 'Staff',       resourceId: 'staff-9', details: 'Updated Dr. David Wilson status to on_leave',               timestamp: '2026-05-15T09:00:00Z' },
  { id: 'log-8',  userId: 'staff-10', userRole: 'RECEPTIONIST', action: 'PROCESS_PAYMENT',       resource: 'Invoice',     resourceId: 'inv-6', details: 'Processed cash payment of $275 for Michael Brown (INV-0006)', timestamp: '2026-05-18T08:40:00Z' },
  { id: 'log-9',  userId: 'staff-7',  userRole: 'DOCTOR',       action: 'UPDATE_APPOINTMENT',    resource: 'Appointment', resourceId: 'apt-9', details: 'Completed appointment for Isabella Garcia, thyroid panel ordered',timestamp: '2026-05-18T09:32:00Z' },
  { id: 'log-10', userId: 'staff-1',  userRole: 'ADMIN',        action: 'RESTOCK_INVENTORY',     resource: 'Inventory',   resourceId: 'inv-item-9', details: 'Restocked N95 Masks: 3500 units. Supplier: SafeMed Supplies',timestamp: '2026-05-10T11:00:00Z' },
];

// ─── Queue ────────────────────────────────────────────────────────────────────
const queue: QueueEntry[] = [
  { id: 'q-1', tokenNumber: 'Q-001', patientId: 'pat-11', doctorId: 'staff-7', appointmentId: 'apt-10', status: 'waiting',     priority: 'normal',    estimatedWait: 25, checkedInAt: '2026-05-18T11:10:00Z' },
  { id: 'q-2', tokenNumber: 'Q-002', patientId: 'pat-16', doctorId: 'staff-7', appointmentId: 'apt-11', status: 'waiting',     priority: 'normal',    estimatedWait: 55, checkedInAt: '2026-05-18T11:15:00Z' },
  { id: 'q-3', tokenNumber: 'Q-003', patientId: 'pat-18', doctorId: 'staff-6', appointmentId: 'apt-13', status: 'waiting',     priority: 'urgent',    estimatedWait: 10, checkedInAt: '2026-05-18T12:50:00Z' },
  { id: 'q-4', tokenNumber: 'Q-004', patientId: 'pat-13', doctorId: 'staff-2', appointmentId: 'apt-3',  status: 'in_progress', priority: 'normal',    estimatedWait: 0,  checkedInAt: '2026-05-18T09:55:00Z', calledAt: '2026-05-18T10:02:00Z' },
  { id: 'q-5', tokenNumber: 'Q-005', patientId: 'pat-10', doctorId: 'staff-3', appointmentId: 'apt-5',  status: 'called',      priority: 'normal',    estimatedWait: 5,  checkedInAt: '2026-05-18T10:45:00Z', calledAt: '2026-05-18T10:55:00Z' },
];

// ─── Consultation Notes ───────────────────────────────────────────────────────
const consultationNotes: ConsultationNote[] = [
  { id: 'note-1', patientId: 'pat-1',  doctorId: 'staff-2', appointmentId: 'apt-1',  subjective: 'Patient reports occasional dizziness in the morning. No chest pain or shortness of breath. Compliant with medications.', objective: 'BP 138/88 mmHg. HR 72 bpm. Weight stable at 82kg. No edema. Heart sounds normal.', assessment: 'Hypertension - well controlled. Type 2 Diabetes - suboptimal control (HbA1c 7.2%).', plan: 'Continue Amlodipine 5mg. Increase Metformin to 1000mg twice daily. Dietary counseling. Repeat HbA1c in 3 months. Follow-up in 6 weeks.', createdAt: '2026-05-18T09:00:00Z', updatedAt: '2026-05-18T09:00:00Z' },
  { id: 'note-2', patientId: 'pat-9',  doctorId: 'staff-2', appointmentId: 'apt-2',  subjective: 'Patient reports 2-day history of intermittent left-sided chest pressure, worse with exertion, rated 5/10. No radiation. Mild shortness of breath with stairs.', objective: 'BP 145/92 mmHg. HR 80 bpm. SpO2 97%. No acute distress. Heart sounds normal, no murmurs. Lungs clear.', assessment: 'Atypical chest pain - cardiac origin not yet excluded. Need to rule out ACS.', plan: 'Stat cardiac enzymes and ECG ordered. If negative, stress test to be scheduled. Increase Metoprolol to 50mg. Return in 1 week or sooner if symptoms worsen.', createdAt: '2026-05-18T09:45:00Z', updatedAt: '2026-05-18T09:45:00Z' },
  { id: 'note-3', patientId: 'pat-2',  doctorId: 'staff-3', appointmentId: 'apt-4',  subjective: 'Patient experiencing 8-10 migraines per month, lasting 4-6 hours. Sumatriptan providing partial relief. Triggers: stress, poor sleep. Missing work frequently.', objective: 'Alert and oriented. No focal neurological deficits. Neck supple. Cranial nerves intact.', assessment: 'Chronic migraine with poor control on current abortive therapy alone. Preventive therapy indicated.', plan: 'Start Topiramate 25mg at bedtime for 2 weeks, then increase to 50mg. Continue Sumatriptan as abortive. Sleep hygiene counseling. Migraine diary. Follow-up 8 weeks.', createdAt: '2026-05-18T10:30:00Z', updatedAt: '2026-05-18T10:30:00Z' },
  { id: 'note-4', patientId: 'pat-5',  doctorId: 'staff-6', appointmentId: 'apt-12', subjective: 'Sudden onset periumbilical pain for 6 hours, now localized to RLQ. Nausea, no vomiting. Last meal 8 hours ago. Fever 37.9°C at home.', objective: 'T 38.1°C. BP 118/76. HR 94. Abdomen soft, tender at epigastrium. No rebound tenderness. Rovsing sign negative. Murphy sign negative.', assessment: 'Epigastric pain with mild leukocytosis. Appendicitis unlikely. Gastritis probable. Ruled out surgical emergency.', plan: 'Omeprazole 40mg daily x 4 weeks. Avoid NSAIDs. Bland diet. Discharge with instructions. Follow up with GP in 1 week if not improved.', createdAt: '2026-05-18T08:35:00Z', updatedAt: '2026-05-18T08:35:00Z' },
];

// ─── Vitals ───────────────────────────────────────────────────────────────────
const vitals: VitalRecord[] = [
  { id: 'vit-1',  patientId: 'pat-1',  recordedBy: 'staff-13', bloodPressureSystolic: 138, bloodPressureDiastolic: 88, heartRate: 72, temperature: 98.4, weight: 82, height: 175, oxygenSaturation: 98, respiratoryRate: 16, recordedAt: '2026-05-18T08:25:00Z' },
  { id: 'vit-2',  patientId: 'pat-1',  recordedBy: 'staff-13', bloodPressureSystolic: 142, bloodPressureDiastolic: 90, heartRate: 74, temperature: 98.6, weight: 82, height: 175, oxygenSaturation: 97, respiratoryRate: 16, recordedAt: '2026-04-15T08:50:00Z' },
  { id: 'vit-3',  patientId: 'pat-9',  recordedBy: 'staff-15', bloodPressureSystolic: 145, bloodPressureDiastolic: 92, heartRate: 80, temperature: 98.2, weight: 78, height: 180, oxygenSaturation: 97, respiratoryRate: 18, recordedAt: '2026-05-18T08:55:00Z' },
  { id: 'vit-4',  patientId: 'pat-13', recordedBy: 'staff-15', bloodPressureSystolic: 128, bloodPressureDiastolic: 80, heartRate: 68, temperature: 97.8, weight: 71, height: 172, oxygenSaturation: 96, respiratoryRate: 20, recordedAt: '2026-05-18T09:52:00Z' },
  { id: 'vit-5',  patientId: 'pat-5',  recordedBy: 'staff-14', bloodPressureSystolic: 118, bloodPressureDiastolic: 76, heartRate: 94, temperature: 100.6, weight: 75, height: 178, oxygenSaturation: 98, respiratoryRate: 20, recordedAt: '2026-05-18T07:25:00Z' },
  { id: 'vit-6',  patientId: 'pat-2',  recordedBy: 'staff-13', bloodPressureSystolic: 118, bloodPressureDiastolic: 74, heartRate: 66, temperature: 98.6, weight: 62, height: 165, oxygenSaturation: 99, respiratoryRate: 14, recordedAt: '2026-05-18T09:25:00Z' },
  { id: 'vit-7',  patientId: 'pat-3',  recordedBy: 'staff-13', bloodPressureSystolic: 100, bloodPressureDiastolic: 65, heartRate: 90, temperature: 98.8, weight: 22, height: 118, oxygenSaturation: 98, respiratoryRate: 22, recordedAt: '2026-05-18T07:55:00Z' },
  { id: 'vit-8',  patientId: 'pat-6',  recordedBy: 'staff-13', bloodPressureSystolic: 112, bloodPressureDiastolic: 70, heartRate: 64, temperature: 98.2, weight: 58, height: 162, oxygenSaturation: 99, respiratoryRate: 14, recordedAt: '2026-05-18T08:55:00Z' },
  { id: 'vit-9',  patientId: 'pat-10', recordedBy: 'staff-13', bloodPressureSystolic: 120, bloodPressureDiastolic: 78, heartRate: 70, temperature: 98.6, weight: 65, height: 168, oxygenSaturation: 99, respiratoryRate: 16, recordedAt: '2026-05-18T10:42:00Z' },
  { id: 'vit-10', patientId: 'pat-17', recordedBy: 'staff-13', bloodPressureSystolic: 122, bloodPressureDiastolic: 80, heartRate: 76, temperature: 98.4, weight: 80, height: 182, oxygenSaturation: 98, respiratoryRate: 16, recordedAt: '2026-05-18T13:55:00Z' },
];

// ─── Seed Function ────────────────────────────────────────────────────────────
export function initSeedData(): void {
  if (localStorage.getItem(KEYS.SEEDED) === 'true') return;

  setAll(KEYS.DEPARTMENTS,        departments);
  setAll(KEYS.STAFF,              staff);
  setAll(KEYS.PATIENTS,           patients);
  setAll(KEYS.ROOMS,              rooms);
  setAll(KEYS.APPOINTMENTS,       appointments);
  setAll(KEYS.PRESCRIPTIONS,      prescriptions);
  setAll(KEYS.LAB_ORDERS,         labOrders);
  setAll(KEYS.INVOICES,           invoices);
  setAll(KEYS.INVENTORY,          inventory);
  setAll(KEYS.NOTIFICATIONS,      notifications);
  setAll(KEYS.AUDIT_LOGS,         auditLogs);
  setAll(KEYS.QUEUE,              queue);
  setAll(KEYS.CONSULTATION_NOTES, consultationNotes);
  setAll(KEYS.VITALS,             vitals);

  localStorage.setItem(KEYS.SEEDED, 'true');
}

export function resetSeedData(): void {
  Object.values(KEYS).forEach(key => localStorage.removeItem(key));
  initSeedData();
}
